// Prompt bank: ~50 sentences, graded by difficulty.
// tier 1 = short common words, 2 = full sentences, 3 = punctuation + capitals,
// 4 = numbers + confusable letters.
export const PROMPTS = [
  // ---- tier 1: warm-up ----
  { id: "w01", tier: 1, text: "the cat sat on the mat" },
  { id: "w02", tier: 1, text: "a big red bus" },
  { id: "w03", tier: 1, text: "she runs every day" },
  { id: "w04", tier: 1, text: "my dog likes to play" },
  { id: "w05", tier: 1, text: "we eat lunch at noon" },
  { id: "w06", tier: 1, text: "the sun is very hot" },
  { id: "w07", tier: 1, text: "i read a good book" },
  { id: "w08", tier: 1, text: "birds fly in the sky" },
  { id: "w09", tier: 1, text: "he walks to school" },
  { id: "w10", tier: 1, text: "cold milk tastes good" },
  { id: "w11", tier: 1, text: "the green grass grows fast" },
  { id: "w12", tier: 1, text: "a small ant carries food" },
  // ---- tier 2: sentences ----
  { id: "s01", tier: 2, text: "the quick brown fox jumps over the lazy dog" },
  { id: "s02", tier: 2, text: "pack my box with five dozen liquor jugs" },
  { id: "s03", tier: 2, text: "how vexingly quick daft zebras jump" },
  { id: "s04", tier: 2, text: "practice makes handwriting better every week" },
  { id: "s05", tier: 2, text: "the early bird catches the worm" },
  { id: "s06", tier: 2, text: "slow and steady wins the race" },
  { id: "s07", tier: 2, text: "a journey of a thousand miles begins with one step" },
  { id: "s08", tier: 2, text: "the pen is mightier than the sword" },
  { id: "s09", tier: 2, text: "good handwriting takes patience and practice" },
  { id: "s10", tier: 2, text: "every expert was once a beginner" },
  { id: "s11", tier: 2, text: "write clearly so others can read your thoughts" },
  { id: "s12", tier: 2, text: "the lazy dog slept under the warm porch" },
  { id: "s13", tier: 2, text: "bright stars shine above the quiet town" },
  // ---- tier 3: punctuation + capitals ----
  { id: "p01", tier: 3, text: "Hello, world! Can you read this?" },
  { id: "p02", tier: 3, text: "My name is Alex, and I live in Portland." },
  { id: "p03", tier: 3, text: "Wait — did you really write that?" },
  { id: "p04", tier: 3, text: "She said, \"Please write more neatly.\"" },
  { id: "p05", tier: 3, text: "First, slow down. Then, form each letter." },
  { id: "p06", tier: 3, text: "The meeting starts at nine; don't be late!" },
  { id: "p07", tier: 3, text: "Capitals matter: London, Paris, Tokyo." },
  { id: "p08", tier: 3, text: "Is this legible? Be honest with yourself." },
  { id: "p09", tier: 3, text: "Dr. Evans prescribed rest — and better penmanship." },
  { id: "p10", tier: 3, text: "January, February, March: the cold months." },
  { id: "p11", tier: 3, text: "Keep your letters on the line, not above it." },
  { id: "p12", tier: 3, text: "Excellence is a habit, not an accident." },
  // ---- tier 4: merciless — numbers + confusables ----
  { id: "m01", tier: 4, text: "Call me at 555-0134 before 6pm." },
  { id: "m02", tier: 4, text: "The code 7a9e2 is case sensitive." },
  { id: "m03", tier: 4, text: "Illinois illusions allude to eels." },
  { id: "m04", tier: 4, text: "Minimum aluminum, maximum uranium." },
  { id: "m05", tier: 4, text: "332 pine needles in 11 bundles." },
  { id: "m06", tier: 4, text: "Will Millie willingly fill the mill?" },
  { id: "m07", tier: 4, text: "Unusual azure zebras zigzag zealously." },
  { id: "m08", tier: 4, text: "Order 48 notebooks, 12 pens, 6 erasers." },
  { id: "m09", tier: 4, text: "The 5th of July, 2026, at 3:30pm." },
  { id: "m10", tier: 4, text: "vv vs w: wave the white flag." },
  { id: "m11", tier: 4, text: "rn or m? Turn the worm." },
  { id: "m12", tier: 4, text: "100 bottles of ink on the wall." },
  { id: "m13", tier: 4, text: "gjpqy: the descenders' dungeon." },
];

export const TIER_NAMES = { 1: "Warm-up", 2: "Sentences", 3: "Punctuation", 4: "Merciless" };
